# Generated by Django 5.2.7 on 2025-10-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KGVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL-имя"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("v", "V Series"),
                            ("vr", "VR Series"),
                            ("vh", "VH Series"),
                        ],
                        default="v",
                        max_length=10,
                        verbose_name="Серия",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (RU)",
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (KY)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (EN)",
                    ),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (RU)"
                    ),
                ),
                (
                    "slug_ky",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (KY)"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (EN)"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kg_vehicles/previews/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kg_vehicles/main/",
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "specs_ru",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (RU)",
                    ),
                ),
                (
                    "specs_ky",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (KY)",
                    ),
                ),
                (
                    "specs_en",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (EN)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "[KG] Машина",
                "verbose_name_plural": "[KG] Каталог машин",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KGHeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kg.kgvehicle"
                    ),
                ),
            ],
            options={
                "verbose_name": "[KG] Hero-слайд",
                "verbose_name_plural": "[KG] Hero-слайды",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="KGFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Bishkek", "Бишкек"),
                            ("Osh", "Ош"),
                            ("Chuy", "Чуйская область"),
                            ("Jalal-Abad", "Джалал-Абадская область"),
                            ("Naryn", "Нарынская область"),
                            ("Batken", "Баткенская область"),
                            ("Talas", "Таласская область"),
                            ("Issyk-Kul", "Иссык-Кульская область"),
                        ],
                        max_length=100,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_process", "В процессе"),
                            ("done", "Обработана"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admin_comment", models.TextField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kg_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="kg.kgvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "[KG] Заявка",
                "verbose_name_plural": "[KG] Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KGVehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="kg_vehicles/mini/%Y/%m/")),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mini_images",
                        to="kg.kgvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "[KG] Доп. изображение",
                "verbose_name_plural": "[KG] Доп. изображения",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCardSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="kg_vehicles/card_icons/")),
                ("value_ru", models.CharField(max_length=100)),
                ("value_ky", models.CharField(blank=True, max_length=100)),
                ("value_en", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_specs",
                        to="kg.kgvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "[KG] Характеристика",
                "verbose_name_plural": "[KG] Характеристики",
                "ordering": ["order"],
            },
        ),
    ]
