# Generated by Django 5.2.7 on 2025-10-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kgheroslide",
            name="description_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Краткое описание для Hero-слайда на английском",
                max_length=500,
                verbose_name="Описание (EN)",
            ),
        ),
        migrations.AddField(
            model_name="kgheroslide",
            name="description_ky",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Краткое описание для Hero-слайда на кыргызском",
                max_length=500,
                verbose_name="Описание (KY)",
            ),
        ),
        migrations.AddField(
            model_name="kgheroslide",
            name="description_ru",
            field=models.TextField(
                default="",
                help_text="Краткое описание для Hero-слайда на русском",
                max_length=500,
                verbose_name="Описание (RU)",
            ),
        ),
        migrations.AlterField(
            model_name="kgheroslide",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="kgheroslide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="kgheroslide",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="kgheroslide",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kg.kgvehicle",
                verbose_name="Машина",
            ),
        ),
    ]
