# Generated by Django 5.2.7 on 2025-10-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kg", "0001_initial"),
    ]

    operations = []
