# Generated by Django 5.2.6 on 2025-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0002_kgheroslide_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kgfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': '[KG] Заявки'},
        ),
        migrations.AlterModelOptions(
            name='kgheroslide',
            options={'ordering': ['order'], 'verbose_name': ' Hero-слайд', 'verbose_name_plural': '[KG] Hero-слайды'},
        ),
        migrations.AlterModelOptions(
            name='kgvehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Машина', 'verbose_name_plural': '[KG] Каталог машин'},
        ),
        migrations.AlterModelOptions(
            name='kgvehicleimage',
            options={'ordering': ['order'], 'verbose_name': ' Доп. изображение', 'verbose_name_plural': 'Доп. изображения'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecardspec',
            options={'ordering': ['order'], 'verbose_name': ' Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
    ]
