# Generated by Django 5.2.7 on 2025-10-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kg", "0003_alter_kgfeedback_options_alter_kgheroslide_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IconTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="kg_vehicles/card_icons/", verbose_name="Иконка"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Шаблон иконки",
                "verbose_name_plural": "Шаблоны иконок",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclecardspec",
            options={
                "ordering": ["order"],
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="icon",
            field=models.ImageField(
                upload_to="kg_vehicles/card_icons/", verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="value_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Значение (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="value_ky",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Значение (KY)"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="value_ru",
            field=models.CharField(max_length=100, verbose_name="Значение (RU)"),
        ),
    ]
