# Generated by Django 5.2.7 on 2025-10-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kg", "0004_icontemplate_alter_vehiclecardspec_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclecardspec",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kg_vehicles/card_icons/",
                verbose_name="Иконка",
            ),
        ),
    ]
