# Generated by Django 5.2.7 on 2025-10-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0005_alter_vehiclecardspec_icon'),
    ]

    operations = [
    ]
