# Generated by Django 5.2.6 on 2025-10-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0005_alter_vehiclecardspec_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_ky',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание (KY)'),
        ),
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_ru',
            field=models.TextField(default='', max_length=500, verbose_name='Описание (RU)'),
        ),
    ]
