# Generated by Django 5.2.7 on 2025-10-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg', '0006_sync_existing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kgheroslide',
            options={'ordering': ['order'], 'verbose_name': 'Hero-слайд', 'verbose_name_plural': '[KG] Hero-слайды'},
        ),
        migrations.AlterModelOptions(
            name='kgvehicleimage',
            options={'ordering': ['order'], 'verbose_name': 'Доп. изображение', 'verbose_name_plural': 'Доп. изображения'},
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_dimensions_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты, мм (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_dimensions_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты, мм (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_dimensions_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габариты, мм (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_material_en',
            field=models.TextField(blank=True, verbose_name='Материал надстройки (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_material_ky',
            field=models.TextField(blank=True, verbose_name='Материал надстройки (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_material_ru',
            field=models.TextField(blank=True, verbose_name='Материал надстройки (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_type_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_type_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_type_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='body_volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объем надстройки, куб.м'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='brakes_en',
            field=models.TextField(blank=True, verbose_name='Тормоза (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='brakes_ky',
            field=models.TextField(blank=True, verbose_name='Тормоза (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='brakes_ru',
            field=models.TextField(blank=True, verbose_name='Тормоза (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_category_en',
            field=models.TextField(blank=True, verbose_name='Модель кабины (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_category_ky',
            field=models.TextField(blank=True, verbose_name='Модель кабины (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_category_ru',
            field=models.TextField(blank=True, verbose_name='Модель кабины (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_equipment_en',
            field=models.TextField(blank=True, verbose_name='Комплектация (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_equipment_ky',
            field=models.TextField(blank=True, verbose_name='Комплектация (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='cabin_equipment_ru',
            field=models.TextField(blank=True, verbose_name='Комплектация (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='curb_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Снаряженная масса, кг'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='dimensions_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габаритные размеры, мм (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='dimensions_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габаритные размеры, мм (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='dimensions_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Габаритные размеры, мм (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='engine_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='engine_power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность, л.с.'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объем, л'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_aircondi',
            field=models.BooleanField(default=False, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth + USB'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_multifunction_steering',
            field=models.BooleanField(default=False, verbose_name='Мультируль'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_power_windows',
            field=models.BooleanField(default=False, verbose_name='Электро-стеклоподъемники'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_radio',
            field=models.BooleanField(default=False, verbose_name='Магнитофон'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_remote_control',
            field=models.BooleanField(default=False, verbose_name='Пульт ДУ'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='feature_sleeping_area',
            field=models.BooleanField(default=False, verbose_name='Спальное место'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='fuel_type_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид топлива (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='fuel_type_ky',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид топлива (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='fuel_type_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид топлива (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='gears',
            field=models.CharField(blank=True, max_length=50, verbose_name='Число передач'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='gross_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Полная масса, кг'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='loading_type_en',
            field=models.TextField(blank=True, verbose_name='Вид загрузки (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='loading_type_ky',
            field=models.TextField(blank=True, verbose_name='Вид загрузки (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='loading_type_ru',
            field=models.TextField(blank=True, verbose_name='Вид загрузки (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='payload',
            field=models.CharField(blank=True, max_length=50, verbose_name='Грузоподъемность, кг'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='suspension_en',
            field=models.TextField(blank=True, verbose_name='Подвеска (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='suspension_ky',
            field=models.TextField(blank=True, verbose_name='Подвеска (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='suspension_ru',
            field=models.TextField(blank=True, verbose_name='Подвеска (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='tank_volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объем топливного бака, л'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='tire_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Шины'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='transmission_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='transmission_type_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (EN)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='transmission_type_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (KY)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='transmission_type_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип (RU)'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='wheel_formula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колесная формула'),
        ),
        migrations.AddField(
            model_name='kgvehicle',
            name='wheelbase',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колесная база, мм'),
        ),
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_ky',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Описание (KY)'),
        ),
        migrations.AlterField(
            model_name='kgheroslide',
            name='description_ru',
            field=models.TextField(default='', max_length=500, verbose_name='Описание (RU)'),
        ),
    ]
