# Generated by Django 5.2.7 on 2025-10-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kg", "0007_alter_kgheroslide_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kgheroslide",
            name="description_ru",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Описание (RU)"
            ),
        ),
    ]
