
"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'nested_admin',
    'django_filters',
    'main',          # ← FAW.UZ
    'kg',            # ← FAW.KG
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # ← ДОБАВЬТЕ
    'PAGE_SIZE': 20,
}

LANGUAGE_CODE = 'ru'
USE_I18N = True
USE_L10N = True

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
    ('uz', "O'zbek"),
    ('ky', 'Кыргызский'),
]

# ВАЖНО: Добавьте эти настройки
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_LANGUAGES = ('ru', 'en', 'uz')  # БЕЗ 'ky'!
MODELTRANSLATION_FALLBACK_LANGUAGES = ('ru',)

# Удалите дублирующиеся строки (они у вас повторяются):
# from pathlib import Path  # <- это уже есть в начале файла
# BASE_DIR = Path(file).resolve().parent.parent  # <- это тоже

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

JAZZMIN_SETTINGS = {
    "site_header": "FAW Admin",
    "site_brand": "VUM",
    "site_logo": "images/logo-vum.png",
    "welcome_sign": "Добро пожаловать в админку VUM",
    "search_model": "auth.User",
    "copyright": "VUM",
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "custom_css": "css/custom_admin.css",
    
    "topmenu_links": [
        {"name": "🌐 Сайт", "url": "home", "new_window": True},
    ],
    
    # ИКОНКИ ДЛЯ МОДЕЛЕЙ
    "icons": {
        # Auth
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # FAW.UZ (main)
        "main.News": "fas fa-newspaper",
        "main.NewsBlock": "fas fa-paragraph",
        "main.ContactForm": "fas fa-envelope",
        "main.Vacancy": "fas fa-briefcase",
        "main.JobApplication": "fas fa-file-alt",
        "main.VacancyResponsibility": "fas fa-tasks",
        "main.VacancyRequirement": "fas fa-check-circle",
        "main.VacancyCondition": "fas fa-handshake",
        "main.IdealCandidate": "fas fa-star",
        
        # FAW.KG (kg)
        "kg.KGVehicle": "fas fa-truck",
        "kg.KGVehicleImage": "fas fa-images",
        "kg.VehicleCardSpec": "fas fa-list",
        "kg.KGFeedback": "fas fa-comment-dots",
        "kg.KGHeroSlide": "fas fa-sliders-h",
    },
    
    # ПОРЯДОК ПРИЛОЖЕНИЙ
    "order_with_respect_to": [
        "main",
        "kg", 
        "auth",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # <-- здесь
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],     
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# import os

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static'),
    os.path.join(BASE_DIR, 'kg/static'),   
]

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    'https://faw.kg',
    'https://faw.uz',
    'http://localhost:3000',
    'http://localhost:5173',  # Vite
    'http://127.0.0.1:5173',
    'http://localhost:8080',  # Другие dev серверы
]

CORS_ALLOW_ALL_ORIGINS = True  # ТОЛЬКО ДЛЯ РАЗРАБОТКИ! В продакшене удалить!