# Generated by Django 5.2.7 on 2025-10-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        upload_to="features/icons/", verbose_name="Иконка SVG"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Иконка характеристики",
                "verbose_name_plural": "Иконки характеристик",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название модели"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название модели"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название модели"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название модели"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dump_truck", "Самосвал"),
                            ("tractor", "Тягач"),
                            ("chassis", "Шасси"),
                            ("van", "Фургон"),
                            ("special", "Спецтехника"),
                        ],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="products/main/", verbose_name="Главное изображение"
                    ),
                ),
                (
                    "card_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/cards/",
                        verbose_name="Изображение для карточки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на главной"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Грузовик FAW",
                "verbose_name_plural": "Грузовики FAW",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Категория параметров",
                "verbose_name_plural": "Категории параметров",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Название вакансии"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL-имя"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "short_description_ru",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "short_description_en",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "short_description_uz",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a>',
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "contact_info_ru",
                    models.TextField(
                        default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a>',
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "contact_info_en",
                    models.TextField(
                        default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a>',
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "contact_info_uz",
                    models.TextField(
                        default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a>',
                        null=True,
                        verbose_name="Контактная информация",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Вакансия (UZ)",
                "verbose_name_plural": "Вакансии (UZ)",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Toshkent shahri", "Toshkent shahri"),
                            ("Andijon viloyati", "Andijon viloyati"),
                            ("Buxoro viloyati", "Buxoro viloyati"),
                            ("Fargʻona viloyati", "Fargʻona viloyati"),
                            ("Jizzax viloyati", "Jizzax viloyati"),
                            ("Xorazm viloyati", "Xorazm viloyati"),
                            ("Namangan viloyati", "Namangan viloyati"),
                            ("Navoiy viloyati", "Navoiy viloyati"),
                            ("Qashqadaryo viloyati", "Qashqadaryo viloyati"),
                            ("Samarqand viloyati", "Samarqand viloyati"),
                            ("Sirdaryo viloyati", "Sirdaryo viloyati"),
                            ("Surxondaryo viloyati", "Surxondaryo viloyati"),
                            ("Toshkent viloyati", "Toshkent viloyati"),
                            (
                                "Qoraqalpogʻiston Respublikasi",
                                "Qoraqalpogʻiston Respublikasi",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Регион",
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_process", "В процессе"),
                            ("done", "Обработана"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, verbose_name="Просмотрено (устарело)"
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uz_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Заявка",
                "verbose_name_plural": "[UZ] Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "desc",
                    models.TextField(max_length=500, verbose_name="Краткое описание"),
                ),
                (
                    "desc_ru",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "desc_en",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "desc_uz",
                    models.TextField(
                        max_length=500, null=True, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "author_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="authors/",
                        verbose_name="Фото автора",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/previews/",
                        verbose_name="Главное фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Новость",
                "verbose_name_plural": "[UZ] Новости",
            },
        ),
        migrations.CreateModel(
            name="NewsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("image", "Изображение"),
                            ("youtube", "YouTube видео"),
                            ("video", "Видео файл"),
                        ],
                        max_length=10,
                        verbose_name="Тип блока",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "text_ru",
                    models.TextField(blank=True, null=True, verbose_name="Текст"),
                ),
                (
                    "text_en",
                    models.TextField(blank=True, null=True, verbose_name="Текст"),
                ),
                (
                    "text_uz",
                    models.TextField(blank=True, null=True, verbose_name="Текст"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="YouTube ссылка"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="news/videos/",
                        verbose_name="Видео файл",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="main.news",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Блок новости",
                "verbose_name_plural": "[UZ] Блоки новостей",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductCardSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="Значение")),
                (
                    "value_ru",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Значение"
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Значение"
                    ),
                ),
                (
                    "value_uz",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Значение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.featureicon",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_specs",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика карточки",
                "verbose_name_plural": "Характеристики карточки (4 шт)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Климат контроль, Круиз контроль",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Например: Климат контроль, Круиз контроль",
                        max_length=100,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Например: Климат контроль, Круиз контроль",
                        max_length=100,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Например: Климат контроль, Круиз контроль",
                        max_length=100,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.featureicon",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика с иконкой",
                "verbose_name_plural": "Характеристики с иконками",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Изображение"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галереи",
                "verbose_name_plural": "Галерея",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecificationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_groups",
                        to="main.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.specificationcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа параметров",
                "verbose_name_plural": "Группы параметров",
                "ordering": ["order", "category__order"],
                "unique_together": {("product", "category")},
            },
        ),
        migrations.CreateModel(
            name="ProductParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Например: Мощность двигателя: 300 л.с.",
                        max_length=500,
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(
                        help_text="Например: Мощность двигателя: 300 л.с.",
                        max_length=500,
                        null=True,
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        help_text="Например: Мощность двигателя: 300 л.с.",
                        max_length=500,
                        null=True,
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "text_uz",
                    models.CharField(
                        help_text="Например: Мощность двигателя: 300 л.с.",
                        max_length=500,
                        null=True,
                        verbose_name="Параметр",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="main.productspecificationgroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметры",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Toshkent shahri", "Toshkent shahri"),
                            ("Andijon viloyati", "Andijon viloyati"),
                            ("Buxoro viloyati", "Buxoro viloyati"),
                            ("Fargʻona viloyati", "Fargʻona viloyati"),
                            ("Jizzax viloyati", "Jizzax viloyati"),
                            ("Xorazm viloyati", "Xorazm viloyati"),
                            ("Namangan viloyati", "Namangan viloyati"),
                            ("Navoiy viloyati", "Navoiy viloyati"),
                            ("Qashqadaryo viloyati", "Qashqadaryo viloyati"),
                            ("Samarqand viloyati", "Samarqand viloyati"),
                            ("Sirdaryo viloyati", "Sirdaryo viloyati"),
                            ("Surxondaryo viloyati", "Surxondaryo viloyati"),
                            ("Toshkent viloyati", "Toshkent viloyati"),
                            (
                                "Qoraqalpogʻiston Respublikasi",
                                "Qoraqalpogʻiston Respublikasi",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "resume",
                    models.FileField(upload_to="resumes/%Y/%m/", verbose_name="Резюме"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Рассмотрено"),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий HR"
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ФИО кандидата"
                    ),
                ),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "applicant_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вакансию (UZ)",
                "verbose_name_plural": "Заявки на вакансии (UZ)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VacancyCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Условие")),
                (
                    "text_ru",
                    models.CharField(max_length=500, null=True, verbose_name="Условие"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=500, null=True, verbose_name="Условие"),
                ),
                (
                    "text_uz",
                    models.CharField(max_length=500, null=True, verbose_name="Условие"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="main.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Условие работы",
                "verbose_name_plural": "Условия работы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VacancyIdealCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=500, verbose_name="Качество/Требование"
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Качество/Требование"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Качество/Требование"
                    ),
                ),
                (
                    "text_uz",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Качество/Требование"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideal_candidates",
                        to="main.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Портрет кандидата",
                "verbose_name_plural": "Портрет идеального кандидата",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VacancyRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Требование")),
                (
                    "text_ru",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "text_uz",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="main.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование",
                "verbose_name_plural": "Требования",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VacancyResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
                ("text_ru", models.TextField(null=True, verbose_name="Описание")),
                ("text_en", models.TextField(null=True, verbose_name="Описание")),
                ("text_uz", models.TextField(null=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="main.vacancy",
                        verbose_name="Вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обязанность",
                "verbose_name_plural": "Обязанности",
                "ordering": ["order"],
            },
        ),
    ]
