# Generated by Django 5.2.6 on 2025-10-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('desc', models.TextField(help_text='Краткое описание для карточки новости', max_length=500, verbose_name='Краткое описание')),
                ('desc_en', models.TextField(help_text='Краткое описание для карточки новости', max_length=500, null=True, verbose_name='Краткое описание')),
                ('desc_uz', models.TextField(help_text='Краткое описание для карточки новости', max_length=500, null=True, verbose_name='Краткое описание')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото автора')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='news/previews/', verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('youtube', 'YouTube видео'), ('video', 'Видео файл')], max_length=10, verbose_name='Тип блока')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Фото')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube ссылка')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Видео файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ['order'],
            },
        ),
    ]
