# Generated by Django 5.2.6 on 2025-10-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slogan_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slogan_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slogan_uz',
        ),
    ]
