# Generated by Django 5.2.6 on 2025-10-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecificationgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productspecificationgroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productspecificationgroup',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры машины'},
        ),
        migrations.AddField(
            model_name='productparameter',
            name='category',
            field=models.CharField(choices=[('main', 'Основные параметры'), ('engine', 'Двигатель'), ('weight', 'Весовые параметры'), ('transmission', 'Трансмиссия'), ('brakes', 'Система тормозов и шин'), ('comfort', 'Удобства')], default='main', max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpecificationCategory',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationGroup',
        ),
    ]
