# Generated by Django 5.2.6 on 2025-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='category',
            field=models.CharField(choices=[('main', 'Основные параметры'), ('engine', 'Двигатель'), ('weight', 'Весовые параметры'), ('transmission', 'Трансмиссия'), ('brakes', 'Система тормозов и шин'), ('comfort', 'Удобства'), ('superstructure', 'Надстройка'), ('cabin', 'Кабина'), ('additional', 'Дополнительные параметры')], max_length=50, verbose_name='Категория'),
        ),
    ]
