# Generated by Django 5.2.6 on 2025-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('youtube', 'YouTube видео'), ('video', 'Видео файл')], max_length=10, verbose_name='Тип блока'),
        ),
    ]
