# Generated by Django 5.2.6 on 2025-10-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='value',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='value_ru',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='value_uz',
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(help_text='Например: Климат контроль, Круиз контроль', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_en',
            field=models.CharField(help_text='Например: Климат контроль, Круиз контроль', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_ru',
            field=models.CharField(help_text='Например: Климат контроль, Круиз контроль', max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name_uz',
            field=models.CharField(help_text='Например: Климат контроль, Круиз контроль', max_length=100, null=True, verbose_name='Название'),
        ),
    ]
