# Generated by Django 5.2.7 on 2025-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_productspecificationgroup_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("shatakchi", "Shatakchi mashinalar"),
                    ("samosval", "Samosvallar"),
                    ("maxsus", "Maxsus texnika"),
                    ("furgon", "Avtofurgonlar"),
                    ("shassi", "Shassilar"),
                    ("tiger_v", "Tiger V"),
                    ("tiger_vr", "Tiger VR"),
                ],
                max_length=50,
                verbose_name="Категория",
            ),
        ),
    ]
