# Generated by Django 5.2.6 on 2025-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newsblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(help_text='Краткое описание для карточки новости', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newsblock',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
