# Generated by Django 5.2.6 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productparameter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider_fuel_consumption',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_fuel_consumption_en',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_fuel_consumption_ru',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_fuel_consumption_uz',
            field=models.CharField(blank=True, help_text="Например: '17 L/100km'", max_length=50, null=True, verbose_name='Расход топлива для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 420x210px. Если не указано, используется main_image', null=True, upload_to='products/slider/', verbose_name='Изображение для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем больше число, тем раньше появится в слайдере', verbose_name='Порядок в слайдере'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_power',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_power_en',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_power_ru',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_power_uz',
            field=models.CharField(blank=True, help_text="Например: '185 o.k.'", max_length=50, null=True, verbose_name='Мощность для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_en',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_ru',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_uz',
            field=models.CharField(blank=True, help_text="Например: '434 000 000 sum'", max_length=100, null=True, verbose_name='Цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_year',
            field=models.CharField(default='2025', help_text='Отображается в слайдере', max_length=4, verbose_name='Год для слайдера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Продукт будет добавлен в главный слайдер', verbose_name='Показывать на главной'),
        ),
    ]
