# Generated by Django 5.2.6 on 2025-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_main_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcardspec',
            name='value_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcardspec',
            name='value_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='productcardspec',
            name='value_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Значение'),
        ),
    ]
