# Generated by Django 5.2.6 on 2025-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product_slider_fuel_consumption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmoCRMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="Access Token")),
                ("refresh_token", models.TextField(verbose_name="Refresh Token")),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "amoCRM Токен",
                "verbose_name_plural": "amoCRM Токены",
            },
        ),
        migrations.AddField(
            model_name="contactform",
            name="amocrm_error",
            field=models.TextField(
                blank=True,
                help_text="Текст последней ошибки при отправке",
                null=True,
                verbose_name="Ошибка amoCRM",
            ),
        ),
        migrations.AddField(
            model_name="contactform",
            name="amocrm_lead_id",
            field=models.CharField(
                blank=True,
                help_text="ID лида после успешной отправки",
                max_length=50,
                null=True,
                verbose_name="ID лида в amoCRM",
            ),
        ),
        migrations.AddField(
            model_name="contactform",
            name="amocrm_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отправки в amoCRM"
            ),
        ),
        migrations.AddField(
            model_name="contactform",
            name="amocrm_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("sent", "Успешно отправлено"),
                    ("failed", "Ошибка отправки"),
                ],
                db_index=True,
                default="pending",
                help_text="Статус отправки в amoCRM",
                max_length=20,
                verbose_name="Статус amoCRM",
            ),
        ),
    ]
