# Generated by Django 5.2.6 on 2025-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productcardspec_value_en_productcardspec_value_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(help_text='RU: Присутствует / EN: Available / UZ: Mavjud', max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_en',
            field=models.CharField(help_text='RU: Присутствует / EN: Available / UZ: Mavjud', max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_ru',
            field=models.CharField(help_text='RU: Присутствует / EN: Available / UZ: Mavjud', max_length=100, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='value_uz',
            field=models.CharField(help_text='RU: Присутствует / EN: Available / UZ: Mavjud', max_length=100, null=True, verbose_name='Значение'),
        ),
    ]
