# Generated by Django 5.2.7 on 2025-10-30 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_force_add_contactform"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BecomeADealerPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Qanday qilib diler bo'lish mumkin",
                        max_length=255,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        default="Qanday qilib diler bo'lish mumkin",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="Qanday qilib diler bo'lish mumkin",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        default="Qanday qilib diler bo'lish mumkin",
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                ("intro_text", models.TextField(verbose_name="Вводный текст")),
                (
                    "intro_text_ru",
                    models.TextField(null=True, verbose_name="Вводный текст"),
                ),
                (
                    "intro_text_en",
                    models.TextField(null=True, verbose_name="Вводный текст"),
                ),
                (
                    "intro_text_uz",
                    models.TextField(null=True, verbose_name="Вводный текст"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Potensial diler kompaniyasining minimal tarkibi:",
                        max_length=255,
                        verbose_name="Подзаголовок списка",
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        default="Potensial diler kompaniyasining minimal tarkibi:",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок списка",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        default="Potensial diler kompaniyasining minimal tarkibi:",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок списка",
                    ),
                ),
                (
                    "subtitle_uz",
                    models.CharField(
                        default="Potensial diler kompaniyasining minimal tarkibi:",
                        max_length=255,
                        null=True,
                        verbose_name="Подзаголовок списка",
                    ),
                ),
                ("important_note", models.TextField(verbose_name="Важная заметка")),
                (
                    "important_note_ru",
                    models.TextField(null=True, verbose_name="Важная заметка"),
                ),
                (
                    "important_note_en",
                    models.TextField(null=True, verbose_name="Важная заметка"),
                ),
                (
                    "important_note_uz",
                    models.TextField(null=True, verbose_name="Важная заметка"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        default="+998 71 234-56-78",
                        max_length=50,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@faw.uz", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        default="Toshkent, Abdulla Kaxxar ko'chasi 2А",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_address_ru",
                    models.TextField(
                        default="Toshkent, Abdulla Kaxxar ko'chasi 2А",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_address_en",
                    models.TextField(
                        default="Toshkent, Abdulla Kaxxar ko'chasi 2А",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "contact_address_uz",
                    models.TextField(
                        default="Toshkent, Abdulla Kaxxar ko'chasi 2А",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Страница 'Стать дилером'",
                "verbose_name_plural": "[UZ] Страница 'Стать дилером'",
            },
        ),
        migrations.CreateModel(
            name="DealerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название услуги"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="URL"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Услуга дилера",
                "verbose_name_plural": "Услуги дилеров",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BecomeADealerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="ФИО контактного лица"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Toshkent shahri", "Toshkent shahri"),
                            ("Andijon viloyati", "Andijon viloyati"),
                            ("Buxoro viloyati", "Buxoro viloyati"),
                            ("Fargʻona viloyati", "Fargʻona viloyati"),
                            ("Jizzax viloyati", "Jizzax viloyati"),
                            ("Xorazm viloyati", "Xorazm viloyati"),
                            ("Namangan viloyati", "Namangan viloyati"),
                            ("Navoiy viloyati", "Navoiy viloyati"),
                            ("Qashqadaryo viloyati", "Qashqadaryo viloyati"),
                            ("Samarqand viloyati", "Samarqand viloyati"),
                            ("Sirdaryo viloyati", "Sirdaryo viloyati"),
                            ("Surxondaryo viloyati", "Surxondaryo viloyati"),
                            ("Toshkent viloyati", "Toshkent viloyati"),
                            (
                                "Qoraqalpogʻiston Respublikasi",
                                "Qoraqalpogʻiston Respublikasi",
                            ),
                        ],
                        max_length=100,
                        verbose_name="Регион",
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Сообщение/Вопросы")),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Если уже есть компания",
                        max_length=255,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Опыт в автобизнесе (лет)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_process", "В процессе"),
                            ("done", "Обработана"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Высокий"),
                            ("medium", "Средний"),
                            ("low", "Низкий"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата подачи"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Заявка на дилерство",
                "verbose_name_plural": "[UZ] Заявки на дилерство",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealerRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Требование")),
                (
                    "text_ru",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "text_uz",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Требование"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="main.becomeadealerpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требование",
                "verbose_name_plural": "Требования к дилерам",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("address", models.TextField(verbose_name="Полный адрес")),
                (
                    "address_ru",
                    models.TextField(null=True, verbose_name="Полный адрес"),
                ),
                (
                    "address_en",
                    models.TextField(null=True, verbose_name="Полный адрес"),
                ),
                (
                    "address_uz",
                    models.TextField(null=True, verbose_name="Полный адрес"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Пример: 41.311151",
                        max_digits=9,
                        verbose_name="Широта (latitude)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Пример: 69.279737",
                        max_digits=9,
                        verbose_name="Долгота (longitude)",
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
                ),
                (
                    "working_hours",
                    models.TextField(
                        help_text="Используйте <br> для переноса строки. Пример: Du-Ju: 9:00-20:00<br>Sha: Dam olish",
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "working_hours_ru",
                    models.TextField(
                        help_text="Используйте <br> для переноса строки. Пример: Du-Ju: 9:00-20:00<br>Sha: Dam olish",
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "working_hours_en",
                    models.TextField(
                        help_text="Используйте <br> для переноса строки. Пример: Du-Ju: 9:00-20:00<br>Sha: Dam olish",
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "working_hours_uz",
                    models.TextField(
                        help_text="Используйте <br> для переноса строки. Пример: Du-Ju: 9:00-20:00<br>Sha: Dam olish",
                        null=True,
                        verbose_name="Рабочее время",
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Менеджер"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dealers/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="dealers",
                        to="main.dealerservice",
                        verbose_name="Услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "[UZ] Дилер",
                "verbose_name_plural": "[UZ] Дилеры",
                "ordering": ["order", "city", "name"],
            },
        ),
    ]
