# Generated by Django 5.2.6 on 2025-11-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_amocrmtoken_contactform_amocrm_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('samosval', 'Samosvallar'), ('maxsus', 'Maxsus texnika'), ('furgon', 'Avtofurgonlar'), ('shassi', 'Shassilar'), ('tiger_v', 'Tiger V'), ('tiger_vh', 'Tiger VH'), ('tiger_vr', 'Tiger VR')], max_length=50, verbose_name='Категория'),
        ),
    ]
