# Generated by Django 5.2.6 on 2025-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="visitor_uid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="amoCRM Visitor UID"
            ),
        ),
    ]
