# Generated by Django 5.2.7 on 2025-10-09 08:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_contactform_options_contactform_admin_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название иконки"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="kg_vehicles/features/",
                        verbose_name="Изображение иконки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Иконка особенности",
                "verbose_name_plural": "Иконки особенностей",
            },
        ),
        migrations.CreateModel(
            name="KGVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="URL-имя"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (RU)",
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (KY)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (EN)",
                    ),
                ),
                (
                    "slug_ru",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (RU)"
                    ),
                ),
                (
                    "slug_ky",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (KY)"
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="URL (EN)"
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kg_vehicles/previews/",
                        verbose_name="Превью для каталога",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kg_vehicles/main/",
                        verbose_name="Главное изображение",
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (по умолчанию)",
                    ),
                ),
                (
                    "specs_ru",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (RU)",
                    ),
                ),
                (
                    "specs_ky",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (KY)",
                    ),
                ),
                (
                    "specs_en",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Характеристики (EN)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Машина (KG)",
                "verbose_name_plural": "Машины (KG)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка (UZ)",
                "verbose_name_plural": "Заявки (UZ)",
            },
        ),
        migrations.CreateModel(
            name="KGFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефон должен быть в формате +996XXXXXXXXX",
                                regex="^\\+996\\d{9}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Bishkek", "Бишкек"),
                            ("Osh", "Ош"),
                            ("Chuy", "Чуйская область"),
                            ("Jalal-Abad", "Джалал-Абадская область"),
                            ("Naryn", "Нарынская область"),
                            ("Batken", "Баткенская область"),
                            ("Talas", "Таласская область"),
                            ("Issyk-Kul", "Иссык-Кульская область"),
                        ],
                        max_length=100,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="main.kgvehicle",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка (KG)",
                "verbose_name_plural": "Заявки (KG)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KGVehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="kg_vehicles/mini/%Y/%m/",
                        verbose_name="Мини-изображение",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt текст"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mini_images",
                        to="main.kgvehicle",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мини-изображение машины (KG)",
                "verbose_name_plural": "Мини-изображения машин (KG)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="KGVehicleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.featureicon",
                        verbose_name="Особенность",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_features",
                        to="main.kgvehicle",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность машины (KG)",
                "verbose_name_plural": "Особенности машин (KG)",
                "unique_together": {("vehicle", "feature")},
            },
        ),
    ]
