# Generated by Django 5.2.6 on 2025-10-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contactform_options_contactform_admin_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-имя')),
                ('short_description', models.TextField(blank=True, help_text='Отображается под заголовком', max_length=500, verbose_name='Краткое описание')),
                ('contact_info', models.TextField(default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a> или <a href="tel:+998555086060">+998(55)508-60-60</a>, отражая опыт: конкретных достижений в продажах, развитии дилерской сети, маркетинге; опыта стратегического планирования и управления командой; успешно реализованных проектов (желательно с цифрами).', help_text='Можно использовать HTML', verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вакансия (UZ)',
                'verbose_name_plural': 'Вакансии (UZ)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': '[UZ] Заявка', 'verbose_name_plural': '[UZ] Заявки'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '[UZ] Новость', 'verbose_name_plural': '[UZ] Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsblock',
            options={'ordering': ['order'], 'verbose_name': '[UZ] Блок новости', 'verbose_name_plural': '[UZ] Блоки новостей'},
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Toshkent shahri', 'Toshkent shahri'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ('Fargʻona viloyati', 'Fargʻona viloyati'), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Qoraqalpogʻiston Respublikasi', 'Qoraqalpogʻiston Respublikasi')], max_length=100, verbose_name='Регион')),
                ('resume', models.FileField(help_text='Форматы: PDF, DOC, DOCX, JPG, PNG. Максимум 10 MB', upload_to='resumes/%Y/%m/', verbose_name='Резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Рассмотрено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий HR')),
                ('applicant_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО кандидата')),
                ('applicant_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('applicant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Заявка на вакансию (UZ)',
                'verbose_name_plural': 'Заявки на вакансии (UZ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Например: Конкурентная зарплата + бонусы', max_length=500, verbose_name='Условие')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Условие работы',
                'verbose_name_plural': 'Условия работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyIdealCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Например: Высшее образование', max_length=500, verbose_name='Качество/Требование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_candidates', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Портрет кандидата',
                'verbose_name_plural': 'Портрет идеального кандидата',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Например: Высшее образование (экономика)', max_length=500, verbose_name='Требование')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VacancyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например: Разработка стратегии', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Подробное описание обязанности', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Обязанность',
                'verbose_name_plural': 'Обязанности',
                'ordering': ['order'],
            },
        ),
    ]
