# Generated by Django 5.2.7 on 2025-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_contactform_options_contactform_admin_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "[UZ] Заявка",
                "verbose_name_plural": "[UZ] Заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "[UZ] Новость",
                "verbose_name_plural": "[UZ] Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="newsblock",
            options={
                "ordering": ["order"],
                "verbose_name": "[UZ] Блок новости",
                "verbose_name_plural": "[UZ] Блоки новостей",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="desc",
            field=models.TextField(max_length=500, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_en",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_ru",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_uz",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
