# Generated by Django 5.2.6 on 2025-11-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactform_visitor_uid_alter_contactform_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
