# Generated by Django 5.2.7 on 2025-10-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_add_default_dealer_services"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="becomeadealerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "[UZ] 02. Заявки - Заявка на дилерство",
                "verbose_name_plural": "[UZ] 02. Заявки - Заявки на дилерство",
            },
        ),
        migrations.AlterModelOptions(
            name="becomeadealerpage",
            options={
                "verbose_name": "[UZ] 01. Контент - Страница 'Стать дилером'",
                "verbose_name_plural": "[UZ] 01. Контент - Страница 'Стать дилером'",
            },
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "[UZ] 02. Заявки - Общая заявка",
                "verbose_name_plural": "[UZ] 02. Заявки - Общие заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ["order", "city", "name"],
                "verbose_name": "[UZ] 03. Дилеры - Дилер",
                "verbose_name_plural": "[UZ] 03. Дилеры - Дилеры",
            },
        ),
        migrations.AlterModelOptions(
            name="dealerrequirement",
            options={
                "ordering": ["order"],
                "verbose_name": "Требование",
                "verbose_name_plural": "Требования",
            },
        ),
        migrations.AlterModelOptions(
            name="dealerservice",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "[UZ] 03. Дилеры - Услуга",
                "verbose_name_plural": "[UZ] 03. Дилеры - Услуги дилеров",
            },
        ),
        migrations.AlterModelOptions(
            name="featureicon",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "[UZ] 01. Контент - Иконка",
                "verbose_name_plural": "[UZ] 01. Контент - Иконки",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "[UZ] 02. Заявки - Заявка на вакансию",
                "verbose_name_plural": "[UZ] 02. Заявки - Заявки на вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "[UZ] 01. Контент - Новость",
                "verbose_name_plural": "[UZ] 01. Контент - Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="newsblock",
            options={
                "ordering": ["order"],
                "verbose_name": "Блок новости",
                "verbose_name_plural": "Блоки новостей",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "[UZ] 01. Контент - Грузовик",
                "verbose_name_plural": "[UZ] 01. Контент - Грузовики FAW",
            },
        ),
        migrations.AlterModelOptions(
            name="productcardspec",
            options={
                "ordering": ["order"],
                "verbose_name": "Характеристика карточки",
                "verbose_name_plural": "Характеристики карточки",
            },
        ),
        migrations.AlterModelOptions(
            name="productfeature",
            options={
                "ordering": ["order"],
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики с иконками",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "[UZ] 04. Вакансии - Вакансия",
                "verbose_name_plural": "[UZ] 04. Вакансии - Вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancycondition",
            options={
                "ordering": ["order"],
                "verbose_name": "Условие",
                "verbose_name_plural": "Условия",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancyidealcandidate",
            options={
                "ordering": ["order"],
                "verbose_name": "Портрет кандидата",
                "verbose_name_plural": "Портрет кандидата",
            },
        ),
        migrations.RemoveField(
            model_name="contactform",
            name="is_processed",
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="admin_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Компания"),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="experience_years",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Опыт (лет)"
            ),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="becomeadealerpage",
            name="title",
            field=models.CharField(
                default="Qanday qilib diler bo'lish mumkin",
                max_length=255,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="becomeadealerpage",
            name="title_en",
            field=models.CharField(
                default="Qanday qilib diler bo'lish mumkin",
                max_length=255,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="becomeadealerpage",
            name="title_ru",
            field=models.CharField(
                default="Qanday qilib diler bo'lish mumkin",
                max_length=255,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="becomeadealerpage",
            name="title_uz",
            field=models.CharField(
                default="Qanday qilib diler bo'lish mumkin",
                max_length=255,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="admin_comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="address",
            field=models.TextField(verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="address_en",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="address_ru",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="address_uz",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Пример: 41.311151",
                max_digits=9,
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Пример: 69.279737",
                max_digits=9,
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="working_hours",
            field=models.TextField(
                help_text="Используйте <br> для переноса", verbose_name="Рабочее время"
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="working_hours_en",
            field=models.TextField(
                help_text="Используйте <br> для переноса",
                null=True,
                verbose_name="Рабочее время",
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="working_hours_ru",
            field=models.TextField(
                help_text="Используйте <br> для переноса",
                null=True,
                verbose_name="Рабочее время",
            ),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="working_hours_uz",
            field=models.TextField(
                help_text="Используйте <br> для переноса",
                null=True,
                verbose_name="Рабочее время",
            ),
        ),
        migrations.AlterField(
            model_name="dealerrequirement",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="main.becomeadealerpage",
            ),
        ),
        migrations.AlterField(
            model_name="dealerservice",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="dealerservice",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="dealerservice",
            name="name_ru",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="dealerservice",
            name="name_uz",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="featureicon",
            name="icon",
            field=models.FileField(upload_to="features/icons/", verbose_name="Иконка"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="text",
            field=models.CharField(max_length=500, verbose_name="Параметр"),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="text_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Параметр"),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="text_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Параметр"),
        ),
        migrations.AlterField(
            model_name="productparameter",
            name="text_uz",
            field=models.CharField(max_length=500, null=True, verbose_name="Параметр"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="contact_info",
            field=models.TextField(
                default="Присылайте резюме на info@faw.uz", verbose_name="Контакты"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="contact_info_en",
            field=models.TextField(
                default="Присылайте резюме на info@faw.uz",
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="contact_info_ru",
            field=models.TextField(
                default="Присылайте резюме на info@faw.uz",
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="contact_info_uz",
            field=models.TextField(
                default="Присылайте резюме на info@faw.uz",
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description_en",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description_ru",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description_uz",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vacancycondition",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="main.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="vacancyidealcandidate",
            name="text",
            field=models.CharField(max_length=500, verbose_name="Качество"),
        ),
        migrations.AlterField(
            model_name="vacancyidealcandidate",
            name="text_en",
            field=models.CharField(max_length=500, null=True, verbose_name="Качество"),
        ),
        migrations.AlterField(
            model_name="vacancyidealcandidate",
            name="text_ru",
            field=models.CharField(max_length=500, null=True, verbose_name="Качество"),
        ),
        migrations.AlterField(
            model_name="vacancyidealcandidate",
            name="text_uz",
            field=models.CharField(max_length=500, null=True, verbose_name="Качество"),
        ),
        migrations.AlterField(
            model_name="vacancyidealcandidate",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideal_candidates",
                to="main.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="vacancyrequirement",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="main.vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="vacancyresponsibility",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsibilities",
                to="main.vacancy",
            ),
        ),
    ]
