# Generated by Django 5.2.6 on 2025-10-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_featureicon_kgvehicle_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kgvehicleimage',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительное изображение (KG)', 'verbose_name_plural': 'Дополнительные изображения (KG)'},
        ),
        migrations.AlterField(
            model_name='kgvehicleimage',
            name='image',
            field=models.ImageField(upload_to='kg_vehicles/mini/%Y/%m/', verbose_name='Изображение'),
        ),
    ]
