# Generated by Django 5.2.6 on 2025-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacancy_alter_contactform_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_info_en',
            field=models.TextField(default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a> или <a href="tel:+998555086060">+998(55)508-60-60</a>, отражая опыт: конкретных достижений в продажах, развитии дилерской сети, маркетинге; опыта стратегического планирования и управления командой; успешно реализованных проектов (желательно с цифрами).', help_text='Можно использовать HTML', null=True, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_info_ru',
            field=models.TextField(default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a> или <a href="tel:+998555086060">+998(55)508-60-60</a>, отражая опыт: конкретных достижений в продажах, развитии дилерской сети, маркетинге; опыта стратегического планирования и управления командой; успешно реализованных проектов (желательно с цифрами).', help_text='Можно использовать HTML', null=True, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contact_info_uz',
            field=models.TextField(default='Присылайте своё резюме на <a href="https://hh.uz" target="_blank">hh.uz</a> или на корпоративную почту <a href="mailto:info@faw.uz">info@faw.uz</a> или <a href="tel:+998555086060">+998(55)508-60-60</a>, отражая опыт: конкретных достижений в продажах, развитии дилерской сети, маркетинге; опыта стратегического планирования и управления командой; успешно реализованных проектов (желательно с цифрами).', help_text='Можно использовать HTML', null=True, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Отображается под заголовком', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Отображается под заголовком', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='short_description_uz',
            field=models.TextField(blank=True, help_text='Отображается под заголовком', max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AddField(
            model_name='vacancycondition',
            name='text_en',
            field=models.CharField(help_text='Например: Конкурентная зарплата + бонусы', max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AddField(
            model_name='vacancycondition',
            name='text_ru',
            field=models.CharField(help_text='Например: Конкурентная зарплата + бонусы', max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AddField(
            model_name='vacancycondition',
            name='text_uz',
            field=models.CharField(help_text='Например: Конкурентная зарплата + бонусы', max_length=500, null=True, verbose_name='Условие'),
        ),
        migrations.AddField(
            model_name='vacancyidealcandidate',
            name='text_en',
            field=models.CharField(help_text='Например: Высшее образование', max_length=500, null=True, verbose_name='Качество/Требование'),
        ),
        migrations.AddField(
            model_name='vacancyidealcandidate',
            name='text_ru',
            field=models.CharField(help_text='Например: Высшее образование', max_length=500, null=True, verbose_name='Качество/Требование'),
        ),
        migrations.AddField(
            model_name='vacancyidealcandidate',
            name='text_uz',
            field=models.CharField(help_text='Например: Высшее образование', max_length=500, null=True, verbose_name='Качество/Требование'),
        ),
        migrations.AddField(
            model_name='vacancyrequirement',
            name='text_en',
            field=models.CharField(help_text='Например: Высшее образование (экономика)', max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AddField(
            model_name='vacancyrequirement',
            name='text_ru',
            field=models.CharField(help_text='Например: Высшее образование (экономика)', max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AddField(
            model_name='vacancyrequirement',
            name='text_uz',
            field=models.CharField(help_text='Например: Высшее образование (экономика)', max_length=500, null=True, verbose_name='Требование'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='text_en',
            field=models.TextField(help_text='Подробное описание обязанности', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='text_ru',
            field=models.TextField(help_text='Подробное описание обязанности', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='text_uz',
            field=models.TextField(help_text='Подробное описание обязанности', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='title_en',
            field=models.CharField(blank=True, help_text='Например: Разработка стратегии', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Например: Разработка стратегии', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='vacancyresponsibility',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Например: Разработка стратегии', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
