# Generated by Django 5.2.7 on 2025-10-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_kgvehicleimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KGHeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем раньше показывается",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Показывать ли этот слайд на главной",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Выберите машину для показа в Hero-секции",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.kgvehicle",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд Hero-секции (KG)",
                "verbose_name_plural": "Слайды Hero-секции (KG)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCardSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Загрузите иконку (например: двигатель, вес, объем)",
                        upload_to="kg_vehicles/card_icons/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "value_ru",
                    models.CharField(
                        help_text="Например: 130 л.с., 4×2, Дизель",
                        max_length=100,
                        verbose_name="Значение (RU)",
                    ),
                ),
                (
                    "value_ky",
                    models.CharField(
                        blank=True,
                        help_text="Автоматически переведется, можно исправить",
                        max_length=100,
                        verbose_name="Значение (KY)",
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        blank=True,
                        help_text="Автоматически переведется, можно исправить",
                        max_length=100,
                        verbose_name="Значение (EN)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_specs",
                        to="main.kgvehicle",
                        verbose_name="Машина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика для карточки (KG)",
                "verbose_name_plural": "Характеристики для карточек (KG)",
                "ordering": ["order"],
            },
        ),
    ]
