# Generated by Django 5.2.6 on 2025-12-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productfeature_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, help_text='Выберите категории через запятую. Например: samosval,maxsus', max_length=255, null=True, verbose_name='Категории (множественный выбор)'),
        ),
    ]
