# Generated by Django 5.2.7 on 2025-10-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_contactform_options_alter_news_options_and_more"),
        ("main", "0007_vacancy_contact_info_en_vacancy_contact_info_ru_and_more"),
    ]

    operations = []
