# Generated by Django 5.2.7 on 2025-10-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_becomeadealerapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="becomeadealerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": " - Заявка на дилерство",
                "verbose_name_plural": "Заявки - Заявки на дилерство",
            },
        ),
        migrations.AlterModelOptions(
            name="becomeadealerpage",
            options={
                "verbose_name": "Контент - Страница 'Стать дилером'",
                "verbose_name_plural": "Контент - Страница 'Стать дилером'",
            },
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявки - Общая заявка",
                "verbose_name_plural": "Заявки - Общие заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ["order", "city", "name"],
                "verbose_name": "Дилеры - Дилер",
                "verbose_name_plural": "Дилеры - Дилеры",
            },
        ),
        migrations.AlterModelOptions(
            name="dealerservice",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Дилеры - Услуга",
                "verbose_name_plural": "Дилеры - Услуги дилеров",
            },
        ),
        migrations.AlterModelOptions(
            name="featureicon",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Контент - Иконка",
                "verbose_name_plural": "Контент - Иконки",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявки - Заявка на вакансию",
                "verbose_name_plural": "Заявки - Заявки на вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": " - Новость",
                "verbose_name_plural": "Контент - Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Контент - Грузовик",
                "verbose_name_plural": "Контент - Грузовики FAW",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Вакансии - Вакансия",
                "verbose_name_plural": "Вакансии - Вакансии",
            },
        ),
    ]
