# Generated by Django 5.2.7 on 2025-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_kgheroslide_vehiclecardspec"),
    ]

    operations = [
        migrations.AddField(
            model_name="kgvehicle",
            name="category",
            field=models.CharField(
                choices=[("v", "V Series"), ("vr", "VR Series"), ("vh", "VH Series")],
                default="v",
                help_text="Выберите серию машины (V, VR или VH)",
                max_length=10,
                verbose_name="Серия",
            ),
        ),
    ]
