# Generated by Django 5.2.6 on 2025-10-15 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20251015_1028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uz_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Обработана')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено (устарело)'),
        ),
    ]
