# Generated by Django 5.2.6 on 2025-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": " Dashboard",
                "verbose_name_plural": " Аналитика Dashboard",
                "db_table": "dashboard_proxy_table",
                "managed": False,
                "default_permissions": ("view",),
            },
        ),
    ]
