# Generated by Django 5.2.7 on 2025-10-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_becomeadealerapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="becomeadealerapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка на дилерство",
                "verbose_name_plural": "🤝 Заявки на дилерство",
            },
        ),
        migrations.AlterModelOptions(
            name="becomeadealerpage",
            options={
                "verbose_name": "Страница 'Стать дилером'",
                "verbose_name_plural": "📄 Страница 'Стать дилером'",
            },
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Общая заявка",
                "verbose_name_plural": "📩 Заявки с сайта",
            },
        ),
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ["order", "city", "name"],
                "verbose_name": "Дилер",
                "verbose_name_plural": "🏪 Дилеры",
            },
        ),
        migrations.AlterModelOptions(
            name="dealerservice",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Услуга дилера",
                "verbose_name_plural": "⚙️ Услуги дилеров",
            },
        ),
        migrations.AlterModelOptions(
            name="featureicon",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Иконка",
                "verbose_name_plural": "🎨 Иконки характеристик",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отклик на вакансию",
                "verbose_name_plural": "💼 Отклики на вакансии",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Новость",
                "verbose_name_plural": "📰 Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Грузовик",
                "verbose_name_plural": "🚚 Грузовики FAW",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "👔 Вакансии",
            },
        ),
    ]
