# Generated by Django 5.2.7 on 2025-10-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_merge_20251015_0947"),
        ("main", "0009_contactform_manager_contactform_priority_and_more"),
    ]

    operations = []
