# Generated by Django 5.2.6 on 2025-12-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='referer',
            field=models.CharField(blank=True, help_text='URL страницы, с которой отправлена заявка', max_length=500, null=True, verbose_name='Referer (откуда пришёл)'),
        ),
    ]
