# Generated by Django 5.1.2 on 2026-01-05 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_contactform_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('button_text', models.CharField(default='Batafsil', max_length=50, verbose_name='Текст кнопки')),
                ('button_text_uz', models.CharField(default='Batafsil', max_length=50, null=True, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(default='Batafsil', max_length=50, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(default='Batafsil', max_length=50, null=True, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше в списке', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
