# Generated by Django 5.2.7 on 2025-10-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_becomeadealerapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="becomeadealerpage",
            name="contact_address_ky",
            field=models.TextField(
                default="Toshkent, Abdulla Kaxxar ko'chasi 2А",
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AddField(
            model_name="becomeadealerpage",
            name="important_note_ky",
            field=models.TextField(null=True, verbose_name="Важная заметка"),
        ),
        migrations.AddField(
            model_name="becomeadealerpage",
            name="intro_text_ky",
            field=models.TextField(null=True, verbose_name="Вводный текст"),
        ),
        migrations.AddField(
            model_name="becomeadealerpage",
            name="subtitle_ky",
            field=models.CharField(
                default="Potensial diler kompaniyasining minimal tarkibi:",
                max_length=255,
                null=True,
                verbose_name="Подзаголовок списка",
            ),
        ),
        migrations.AddField(
            model_name="becomeadealerpage",
            name="title_ky",
            field=models.CharField(
                default="Qanday qilib diler bo'lish mumkin",
                max_length=255,
                null=True,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="address_ky",
            field=models.TextField(null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="dealer",
            name="working_hours_ky",
            field=models.TextField(
                help_text="Используйте <br> для переноса",
                null=True,
                verbose_name="Рабочее время",
            ),
        ),
        migrations.AddField(
            model_name="dealerrequirement",
            name="text_ky",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Требование"
            ),
        ),
        migrations.AddField(
            model_name="dealerservice",
            name="name_ky",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="desc_ky",
            field=models.TextField(
                max_length=500, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="newsblock",
            name="text_ky",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ky",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название модели"
            ),
        ),
        migrations.AddField(
            model_name="productcardspec",
            name="value_ky",
            field=models.CharField(max_length=100, null=True, verbose_name="Значение"),
        ),
        migrations.AddField(
            model_name="productfeature",
            name="name_ky",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="productparameter",
            name="text_ky",
            field=models.CharField(max_length=500, null=True, verbose_name="Параметр"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="contact_info_ky",
            field=models.TextField(
                default="Присылайте резюме на info@faw.uz",
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="short_description_ky",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="title_ky",
            field=models.CharField(max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="vacancycondition",
            name="text_ky",
            field=models.CharField(max_length=500, null=True, verbose_name="Условие"),
        ),
        migrations.AddField(
            model_name="vacancyidealcandidate",
            name="text_ky",
            field=models.CharField(max_length=500, null=True, verbose_name="Качество"),
        ),
        migrations.AddField(
            model_name="vacancyrequirement",
            name="text_ky",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Требование"
            ),
        ),
        migrations.AddField(
            model_name="vacancyresponsibility",
            name="text_ky",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="vacancyresponsibility",
            name="title_ky",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
