# Generated by Django 5.2.6 on 2025-10-18 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20251015_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('icon', models.FileField(upload_to='features/icons/', verbose_name='Иконка SVG')),
                ('category', models.CharField(blank=True, help_text='Для группировки (Комфорт, Безопасность и т.д.)', max_length=50, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаблон характеристики',
                'verbose_name_plural': 'Шаблоны характеристик',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модели')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название модели')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('dump_truck', 'Самосвал'), ('tractor', 'Тягач'), ('chassis', 'Шасси'), ('van', 'Фургон'), ('special', 'Спецтехника')], max_length=50, verbose_name='Категория')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('main_description', models.TextField(blank=True, verbose_name='Основное описание')),
                ('main_description_ru', models.TextField(blank=True, null=True, verbose_name='Основное описание')),
                ('main_description_en', models.TextField(blank=True, null=True, verbose_name='Основное описание')),
                ('main_description_uz', models.TextField(blank=True, null=True, verbose_name='Основное описание')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('slogan_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('slogan_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Главное изображение')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='products/cards/', verbose_name='Изображение для карточки')),
                ('wheel_formula', models.CharField(default='4x2', max_length=20, verbose_name='Колесная формула')),
                ('fuel_type', models.CharField(default='Dizel', max_length=50, verbose_name='Тип топлива')),
                ('fuel_type_ru', models.CharField(default='Dizel', max_length=50, null=True, verbose_name='Тип топлива')),
                ('fuel_type_en', models.CharField(default='Dizel', max_length=50, null=True, verbose_name='Тип топлива')),
                ('fuel_type_uz', models.CharField(default='Dizel', max_length=50, null=True, verbose_name='Тип топлива')),
                ('load_capacity', models.CharField(max_length=50, verbose_name='Грузоподъемность')),
                ('load_capacity_ru', models.CharField(max_length=50, null=True, verbose_name='Грузоподъемность')),
                ('load_capacity_en', models.CharField(max_length=50, null=True, verbose_name='Грузоподъемность')),
                ('load_capacity_uz', models.CharField(max_length=50, null=True, verbose_name='Грузоподъемность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Грузовик FAW',
                'verbose_name_plural': 'Грузовики FAW',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='products/card_icons/', verbose_name='Иконка')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=100, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_specs', to='main.product')),
            ],
            options={
                'verbose_name': 'Характеристика карточки',
                'verbose_name_plural': 'Характеристики карточки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='products/feature_icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('value', models.CharField(default='Mavjud', max_length=100, verbose_name='Значение')),
                ('value_ru', models.CharField(default='Mavjud', max_length=100, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(default='Mavjud', max_length=100, null=True, verbose_name='Значение')),
                ('value_uz', models.CharField(default='Mavjud', max_length=100, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.product')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.product')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductParameterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название категории')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название категории')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название категории')),
                ('is_expanded', models.BooleanField(default=False, verbose_name='Развернута по умолчанию')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_categories', to='main.product')),
            ],
            options={
                'verbose_name': 'Категория параметров',
                'verbose_name_plural': 'Категории параметров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Параметр')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Параметр')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Параметр')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Параметр')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('value_ru', models.CharField(max_length=500, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(max_length=500, null=True, verbose_name='Значение')),
                ('value_uz', models.CharField(max_length=500, null=True, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.productparametercategory')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['order'],
            },
        ),
    ]
