# Generated by Django 5.2.6 on 2026-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Page", "Статическая страница"),
                            ("Post", "Новость"),
                            ("Product", "Продукт"),
                            ("Vacancy", "Вакансия"),
                            ("Dealer", "Дилер"),
                        ],
                        help_text="Выберите категорию страницы",
                        max_length=50,
                        verbose_name="Тип страницы",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Уникальный идентификатор страницы",
                        max_length=100,
                        verbose_name="Ключ страницы",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок для поисковиков (оптимально: 50-70 символов)",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(
                        help_text="Заголовок для поисковиков (оптимально: 50-70 символов)",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        help_text="Заголовок для поисковиков (оптимально: 50-70 символов)",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Заголовок для поисковиков (оптимально: 50-70 символов)",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Описание для поисковиков (оптимально: 150-250 символов)",
                        max_length=1000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        help_text="Описание для поисковиков (оптимально: 150-250 символов)",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        help_text="Описание для поисковиков (оптимально: 150-250 символов)",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Описание для поисковиков (оптимально: 150-250 символов)",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую (необязательно)",
                        max_length=500,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_uz",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую (необязательно)",
                        max_length=500,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_ru",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую (необязательно)",
                        max_length=500,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую (необязательно)",
                        max_length=500,
                        null=True,
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для соцсетей (если пусто - используется Title)",
                        max_length=255,
                        null=True,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_title_uz",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для соцсетей (если пусто - используется Title)",
                        max_length=255,
                        null=True,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_title_ru",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для соцсетей (если пусто - используется Title)",
                        max_length=255,
                        null=True,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для соцсетей (если пусто - используется Title)",
                        max_length=255,
                        null=True,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True,
                        help_text="Описание для соцсетей (если пусто - используется Description)",
                        max_length=1000,
                        null=True,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_description_uz",
                    models.TextField(
                        blank=True,
                        help_text="Описание для соцсетей (если пусто - используется Description)",
                        max_length=1000,
                        null=True,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Описание для соцсетей (если пусто - используется Description)",
                        max_length=1000,
                        null=True,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_description_en",
                    models.TextField(
                        blank=True,
                        help_text="Описание для соцсетей (если пусто - используется Description)",
                        max_length=1000,
                        null=True,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_url",
                    models.URLField(
                        blank=True,
                        help_text="Полная ссылка на страницу (генерируется автоматически)",
                        null=True,
                        verbose_name="OG URL",
                    ),
                ),
                (
                    "og_type",
                    models.CharField(
                        choices=[
                            ("website", "Website - Обычный сайт"),
                            ("article", "Article - Статья, новость"),
                            ("product", "Product - Товар, продукт"),
                            ("profile", "Profile - Профиль"),
                            ("video.movie", "Video - Видео"),
                            ("music.song", "Music - Музыка"),
                            ("book", "Book - Книга"),
                        ],
                        default="website",
                        help_text="Тип контента для соцсетей",
                        max_length=50,
                        verbose_name="OG Type",
                    ),
                ),
                (
                    "og_site_name",
                    models.CharField(
                        default="FAW Uzbekistan",
                        help_text="Название сайта/компании",
                        max_length=100,
                        verbose_name="OG Site Name",
                    ),
                ),
                (
                    "og_site_name_uz",
                    models.CharField(
                        default="FAW Uzbekistan",
                        help_text="Название сайта/компании",
                        max_length=100,
                        null=True,
                        verbose_name="OG Site Name",
                    ),
                ),
                (
                    "og_site_name_ru",
                    models.CharField(
                        default="FAW Uzbekistan",
                        help_text="Название сайта/компании",
                        max_length=100,
                        null=True,
                        verbose_name="OG Site Name",
                    ),
                ),
                (
                    "og_site_name_en",
                    models.CharField(
                        default="FAW Uzbekistan",
                        help_text="Название сайта/компании",
                        max_length=100,
                        null=True,
                        verbose_name="OG Site Name",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Картинка для соцсетей (рекомендуется: 1200x630px)",
                        null=True,
                        upload_to="seo/og_images/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Использовать эти мета-данные на сайте",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "SEO - Мета-данные страницы",
                "verbose_name_plural": "SEO - Мета-данные страниц",
                "ordering": ["model", "key"],
                "unique_together": {("model", "key")},
            },
        ),
    ]
