# Generated by Django 5.2.6 on 2025-10-18 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_featuretemplate_product_productcardspec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('icon', models.FileField(upload_to='features/icons/', verbose_name='Иконка SVG')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Иконка характеристики',
                'verbose_name_plural': 'Иконки характеристик',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureTemplate',
        ),
        migrations.RemoveField(
            model_name='productparametercategory',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='productcardspec',
            options={'ordering': ['order'], 'verbose_name': 'Характеристика карточки', 'verbose_name_plural': 'Характеристики карточки (4 шт)'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={'ordering': ['order'], 'verbose_name': 'Характеристика с иконкой', 'verbose_name_plural': 'Характеристики с иконками'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuel_type_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='air_conditioner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='product',
            name='air_conditioner_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='product',
            name='air_conditioner_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='product',
            name='air_conditioner_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Аудиосистема'),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_system_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аудиосистема'),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_system_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аудиосистема'),
        ),
        migrations.AddField(
            model_name='product',
            name='audio_system_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аудиосистема'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_booster',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тормозной усилитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_booster_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозной усилитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_booster_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозной усилитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_booster_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозной усилитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тормозная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_system_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_system_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='brake_system_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тормозная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='curb_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Снаряжённая масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='curb_weight_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Снаряжённая масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='curb_weight_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Снаряжённая масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='curb_weight_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Снаряжённая масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='differential',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дифференциал'),
        ),
        migrations.AddField(
            model_name='product',
            name='differential_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дифференциал'),
        ),
        migrations.AddField(
            model_name='product',
            name='differential_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дифференциал'),
        ),
        migrations.AddField(
            model_name='product',
            name='differential_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дифференциал'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Длина×ширина×высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина×ширина×высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина×ширина×высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Длина×ширина×высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_axle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ведущая ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_axle_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ведущая ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_axle_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ведущая ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='drive_axle_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ведущая ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Экологический класс'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_class_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Экологический класс'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_class_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Экологический класс'),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_class_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Экологический класс'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power',
            field=models.CharField(blank=True, max_length=50, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_axle_load',
            field=models.CharField(blank=True, max_length=50, verbose_name='Нагрузка на переднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_axle_load_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на переднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_axle_load_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на переднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_axle_load_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на переднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_consumption_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расход топлива'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_tank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объем топливного бака'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_tank_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем топливного бака'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_tank_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем топливного бака'),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_tank_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем топливного бака'),
        ),
        migrations.AddField(
            model_name='product',
            name='gearbox',
            field=models.CharField(blank=True, max_length=50, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='gearbox_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='gearbox_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='gearbox_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='product',
            name='hand_brake',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стояночный тормоз'),
        ),
        migrations.AddField(
            model_name='product',
            name='hand_brake_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стояночный тормоз'),
        ),
        migrations.AddField(
            model_name='product',
            name='hand_brake_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стояночный тормоз'),
        ),
        migrations.AddField(
            model_name='product',
            name='hand_brake_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стояночный тормоз'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_axle_load',
            field=models.CharField(blank=True, max_length=50, verbose_name='Нагрузка на заднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_axle_load_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на заднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_axle_load_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на заднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_axle_load_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Нагрузка на заднюю ось'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeper',
            field=models.CharField(blank=True, max_length=50, verbose_name='Спальное место'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeper_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeper_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeper_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Спальное место'),
        ),
        migrations.AddField(
            model_name='product',
            name='steering_buttons',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кнопки на руле'),
        ),
        migrations.AddField(
            model_name='product',
            name='steering_buttons_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопки на руле'),
        ),
        migrations.AddField(
            model_name='product',
            name='steering_buttons_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопки на руле'),
        ),
        migrations.AddField(
            model_name='product',
            name='steering_buttons_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кнопки на руле'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер шин'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_size_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер шин'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_size_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер шин'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_size_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер шин'),
        ),
        migrations.AddField(
            model_name='product',
            name='torque',
            field=models.CharField(blank=True, max_length=50, verbose_name='Крутящий момент'),
        ),
        migrations.AddField(
            model_name='product',
            name='torque_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Крутящий момент'),
        ),
        migrations.AddField(
            model_name='product',
            name='torque_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Крутящий момент'),
        ),
        migrations.AddField(
            model_name='product',
            name='torque_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Крутящий момент'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Полная масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полная масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полная масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Полная масса'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_base',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колесная база'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_base_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная база'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_base_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная база'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_base_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная база'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_formula_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная формула'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_formula_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная формула'),
        ),
        migrations.AddField(
            model_name='product',
            name='wheel_formula_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Колесная формула'),
        ),
        migrations.AddField(
            model_name='product',
            name='window_lifters',
            field=models.CharField(blank=True, max_length=50, verbose_name='Стеклоподъёмники'),
        ),
        migrations.AddField(
            model_name='product',
            name='window_lifters_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стеклоподъёмники'),
        ),
        migrations.AddField(
            model_name='product',
            name='window_lifters_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стеклоподъёмники'),
        ),
        migrations.AddField(
            model_name='product',
            name='window_lifters_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стеклоподъёмники'),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Грузоподъёмность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_capacity_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Грузоподъёмность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_capacity_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Грузоподъёмность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='load_capacity_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Грузоподъёмность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wheel_formula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Колесная формула'),
        ),
        migrations.AlterField(
            model_name='productcardspec',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.featureicon'),
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
        migrations.DeleteModel(
            name='ProductParameterCategory',
        ),
    ]
