# Generated by Django 5.2.6 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_pagemeta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagemeta",
            options={
                "ordering": ["model", "key_order", "key"],
                "verbose_name": "SEO - Мета-данные страницы",
                "verbose_name_plural": "SEO - Мета-данные страниц",
            },
        ),
        migrations.AddField(
            model_name="pagemeta",
            name="key_order",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Автоматически заполняется из key для правильной сортировки",
                null=True,
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="pagemeta",
            name="model",
            field=models.CharField(
                choices=[
                    ("Page", "Статическая страница"),
                    ("Post", "Новость"),
                    ("Product", "Продукт"),
                ],
                help_text="Выберите категорию страницы",
                max_length=50,
                verbose_name="Тип страницы",
            ),
        ),
    ]
