# Generated by Django 5.2.7 on 2025-10-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_dealer_created_at_alter_dealer_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="becomeadealerpage",
            name="contact_address_ky",
        ),
        migrations.RemoveField(
            model_name="becomeadealerpage",
            name="important_note_ky",
        ),
        migrations.RemoveField(
            model_name="becomeadealerpage",
            name="intro_text_ky",
        ),
        migrations.RemoveField(
            model_name="becomeadealerpage",
            name="subtitle_ky",
        ),
        migrations.RemoveField(
            model_name="becomeadealerpage",
            name="title_ky",
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="address_ky",
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="working_hours_ky",
        ),
        migrations.RemoveField(
            model_name="dealerrequirement",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="dealerservice",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="news",
            name="desc_ky",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_ky",
        ),
        migrations.RemoveField(
            model_name="newsblock",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="product",
            name="title_ky",
        ),
        migrations.RemoveField(
            model_name="productcardspec",
            name="value_ky",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="name_ky",
        ),
        migrations.RemoveField(
            model_name="productparameter",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="contact_info_ky",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="short_description_ky",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="title_ky",
        ),
        migrations.RemoveField(
            model_name="vacancycondition",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="vacancyidealcandidate",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="vacancyrequirement",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="vacancyresponsibility",
            name="text_ky",
        ),
        migrations.RemoveField(
            model_name="vacancyresponsibility",
            name="title_ky",
        ),
    ]
