# Generated by Django 5.2.7 on 2025-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_becomeadealerpage_contact_address_ky_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Показывать новость на сайте",
                verbose_name="Активна",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Чем больше число, тем выше в списке",
                verbose_name="Порядок",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Генерируется автоматически из заголовка",
                max_length=255,
                unique=True,
                verbose_name="URL",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc",
            field=models.TextField(
                help_text="Отображается в превью новости",
                max_length=200,
                verbose_name="Краткое описание для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_en",
            field=models.TextField(
                help_text="Отображается в превью новости",
                max_length=200,
                null=True,
                verbose_name="Краткое описание для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_ru",
            field=models.TextField(
                help_text="Отображается в превью новости",
                max_length=200,
                null=True,
                verbose_name="Краткое описание для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="desc_uz",
            field=models.TextField(
                help_text="Отображается в превью новости",
                max_length=200,
                null=True,
                verbose_name="Краткое описание для карточки",
            ),
        ),
    ]
