# Generated by Django 5.2.6 on 2026-01-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_pagemeta_options_pagemeta_key_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagemeta",
            options={
                "ordering": ["-is_active", "-updated_at", "model", "key_order", "key"],
                "verbose_name": "SEO - Мета-данные страницы",
                "verbose_name_plural": "SEO - Мета-данные страниц",
            },
        ),
        migrations.AddField(
            model_name="pagemeta",
            name="og_url_en",
            field=models.URLField(
                blank=True,
                help_text="Полная ссылка на страницу (генерируется автоматически)",
                null=True,
                verbose_name="OG URL",
            ),
        ),
        migrations.AddField(
            model_name="pagemeta",
            name="og_url_ru",
            field=models.URLField(
                blank=True,
                help_text="Полная ссылка на страницу (генерируется автоматически)",
                null=True,
                verbose_name="OG URL",
            ),
        ),
        migrations.AddField(
            model_name="pagemeta",
            name="og_url_uz",
            field=models.URLField(
                blank=True,
                help_text="Полная ссылка на страницу (генерируется автоматически)",
                null=True,
                verbose_name="OG URL",
            ),
        ),
    ]
