# Generated by Django 5.2.6 on 2025-10-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_specificationcategory_remove_featureicon_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationcategory',
            name='icon',
        ),
    ]
