# Generated by Django 5.1.2 on 2026-02-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_pagemeta_options_pagemeta_og_url_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в узбекских сумах для отображения диапазона цен в категориях', max_digits=15, null=True, verbose_name='Цена (UZS)'),
        ),
    ]
