# Generated by Django 5.2.7 on 2025-11-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_news_is_active_news_order_news_slug_news_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-order", "-created_at"],
                "verbose_name": " - Новость",
                "verbose_name_plural": "Контент - Новости",
            },
        ),
    ]
