# Generated by Django 5.2.7 on 2025-11-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_news_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(
                help_text="Введите дату публикации вручную",
                verbose_name="Дата публикации",
            ),
        ),
    ]
