# Generated by Django 5.1.2 on 2026-02-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_is_from',
            field=models.BooleanField(default=False, help_text="Если включено, перед ценой будет отображаться слово 'от'", verbose_name="Цена 'от'"),
        ),
    ]
