# Generated by Django 5.2.7 on 2025-11-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_news_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsblock",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок H3 перед текстовым блоком",
                max_length=500,
                null=True,
                verbose_name="Заголовок (необязательно)",
            ),
        ),
    ]
