# Generated by Django 5.1.2 on 2026-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_price_is_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_uz', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'FAQ — вопрос',
                'verbose_name_plural': 'FAQ — вопросы',
                'ordering': ['order'],
            },
        ),
    ]
