# Generated by Django 5.2.7 on 2025-11-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_newsblock_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsblock",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Заголовок H3 перед текстовым блоком",
                max_length=500,
                null=True,
                verbose_name="Заголовок (необязательно)",
            ),
        ),
        migrations.AddField(
            model_name="newsblock",
            name="title_ru",
            field=models.CharField(
                blank=True,
                help_text="Заголовок H3 перед текстовым блоком",
                max_length=500,
                null=True,
                verbose_name="Заголовок (необязательно)",
            ),
        ),
        migrations.AddField(
            model_name="newsblock",
            name="title_uz",
            field=models.CharField(
                blank=True,
                help_text="Заголовок H3 перед текстовым блоком",
                max_length=500,
                null=True,
                verbose_name="Заголовок (необязательно)",
            ),
        ),
    ]
