# Generated by Django 5.2.6 on 2026-04-28 04:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_faqitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        help_text="Получить у @BotFather. При смене — бот автоматически переключится на новый.",
                        max_length=200,
                        verbose_name="Токен бота",
                    ),
                ),
                (
                    "bot_username",
                    models.CharField(
                        blank=True,
                        help_text="Например: faw_uz_bot (без @)",
                        max_length=100,
                        null=True,
                        verbose_name="Username бота",
                    ),
                ),
                (
                    "notify_chat_id",
                    models.CharField(
                        help_text="ID группы/канала куда летят уведомления о заявках из бота",
                        max_length=50,
                        verbose_name="Chat ID для уведомлений",
                    ),
                ),
                (
                    "notify_chat_id_2",
                    models.CharField(
                        blank=True,
                        help_text="Дополнительный чат, например личка старшего менеджера",
                        max_length=50,
                        null=True,
                        verbose_name="Chat ID для уведомлений (резерв)",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        default="https://faw.uz",
                        help_text="Используется в кнопках 'Подробнее на сайте'",
                        verbose_name="URL сайта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Если выключить — бот перестанет отвечать на сообщения",
                        verbose_name="Бот активен",
                    ),
                ),
                (
                    "use_webhook",
                    models.BooleanField(
                        default=False,
                        help_text="True = Webhook (прод), False = Polling (локально)",
                        verbose_name="Использовать Webhook",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Например: https://faw.uz/bot/webhook/",
                        null=True,
                        verbose_name="Webhook URL",
                    ),
                ),
                (
                    "work_hours_start",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="Время по Ташкенту (UTC+5)",
                        verbose_name="Начало рабочего дня",
                    ),
                ),
                (
                    "work_hours_end",
                    models.TimeField(
                        default=datetime.time(18, 0),
                        help_text="Время по Ташкенту (UTC+5)",
                        verbose_name="Конец рабочего дня",
                    ),
                ),
                (
                    "catalog_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF файл каталога. Отправляется пользователю по кнопке 'Скачать каталог'",
                        null=True,
                        upload_to="bot/catalog/",
                        verbose_name="PDF каталог",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Конфигурация",
                "verbose_name_plural": "Бот — Конфигурация",
            },
        ),
        migrations.CreateModel(
            name="BotContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_main",
                    models.CharField(
                        default="+998 71 000-00-00",
                        help_text="Например: +998 71 234-56-78",
                        max_length=50,
                        verbose_name="Основной телефон",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Дополнительный телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@faw.uz", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address_ru",
                    models.TextField(
                        default="г. Ташкент, ул. Абдулла Каххара 2А",
                        verbose_name="Адрес (RU)",
                    ),
                ),
                (
                    "address_uz",
                    models.TextField(
                        default="Toshkent sh., Abdulla Kaxxar ko'chasi 2A",
                        verbose_name="Адрес (UZ)",
                    ),
                ),
                (
                    "address_en",
                    models.TextField(blank=True, null=True, verbose_name="Адрес (EN)"),
                ),
                (
                    "working_hours_ru",
                    models.CharField(
                        default="Пн–Пт: 09:00–18:00, Сб: 09:00–14:00",
                        max_length=200,
                        verbose_name="Рабочее время (RU)",
                    ),
                ),
                (
                    "working_hours_uz",
                    models.CharField(
                        default="Du–Ju: 09:00–18:00, Sha: 09:00–14:00",
                        max_length=200,
                        verbose_name="Рабочее время (UZ)",
                    ),
                ),
                (
                    "working_hours_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Рабочее время (EN)",
                    ),
                ),
                (
                    "telegram_channel",
                    models.CharField(
                        blank=True,
                        help_text="Например: https://t.me/faw_uzbekistan",
                        max_length=100,
                        null=True,
                        verbose_name="Telegram канал",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        help_text="Например: https://instagram.com/faw.uz",
                        max_length=100,
                        null=True,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True,
                        help_text="Ссылка на канал",
                        max_length=200,
                        null=True,
                        verbose_name="YouTube",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="LinkedIn"
                    ),
                ),
                (
                    "website",
                    models.URLField(default="https://faw.uz", verbose_name="Сайт"),
                ),
                (
                    "map_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на офис в 2GIS или Google Maps",
                        null=True,
                        verbose_name="Ссылка на карту (2GIS/Google)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Бот — Контакты",
                "verbose_name_plural": "Бот — Контакты",
            },
        ),
        migrations.CreateModel(
            name="BotMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("catalog", "🚗 Каталог"),
                            ("dealers", "🏢 Дилеры"),
                            ("news", "📰 Новости"),
                            ("promotions", "🎯 Акции"),
                            ("test_drive", "📋 Тест-драйв"),
                            ("lead", "📞 Оставить заявку"),
                            ("leasing", "💰 Лизинг"),
                            ("faq", "❓ FAQ"),
                            ("contacts", "📍 Контакты"),
                            ("profile", "👤 Профиль"),
                            ("language", "🌐 Язык"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "label_ru",
                    models.CharField(max_length=50, verbose_name="Название (RU)"),
                ),
                (
                    "label_uz",
                    models.CharField(max_length=50, verbose_name="Название (UZ)"),
                ),
                (
                    "label_en",
                    models.CharField(max_length=50, verbose_name="Название (EN)"),
                ),
                (
                    "emoji",
                    models.CharField(default="📌", max_length=5, verbose_name="Эмодзи"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Чем меньше число — тем выше кнопка",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Скрыть пункт меню без удаления",
                        verbose_name="Активен",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Пункт меню",
                "verbose_name_plural": "Бот — Меню",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="becomeadealerapplication",
            name="region",
            field=models.CharField(
                choices=[
                    ("tashkent_city", "Toshkent shahri"),
                    ("andijan", "Andijon viloyati"),
                    ("bukhara", "Buxoro viloyati"),
                    ("fergana", "Farg'ona viloyati"),
                    ("jizzakh", "Jizzax viloyati"),
                    ("khorezm", "Xorazm viloyati"),
                    ("namangan", "Namangan viloyati"),
                    ("navoi", "Navoiy viloyati"),
                    ("kashkadarya", "Qashqadaryo viloyati"),
                    ("samarkand", "Samarqand viloyati"),
                    ("syrdarya", "Sirdaryo viloyati"),
                    ("surkhandarya", "Surxondaryo viloyati"),
                    ("tashkent_region", "Toshkent viloyati"),
                    ("karakalpakstan", "Qoraqalpog'iston Respublikasi"),
                ],
                max_length=100,
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="region",
            field=models.CharField(
                choices=[
                    ("tashkent_city", "Toshkent shahri"),
                    ("andijan", "Andijon viloyati"),
                    ("bukhara", "Buxoro viloyati"),
                    ("fergana", "Farg'ona viloyati"),
                    ("jizzakh", "Jizzax viloyati"),
                    ("khorezm", "Xorazm viloyati"),
                    ("namangan", "Namangan viloyati"),
                    ("navoi", "Navoiy viloyati"),
                    ("kashkadarya", "Qashqadaryo viloyati"),
                    ("samarkand", "Samarqand viloyati"),
                    ("syrdarya", "Sirdaryo viloyati"),
                    ("surkhandarya", "Surxondaryo viloyati"),
                    ("tashkent_region", "Toshkent viloyati"),
                    ("karakalpakstan", "Qoraqalpog'iston Respublikasi"),
                ],
                max_length=100,
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="region",
            field=models.CharField(
                choices=[
                    ("tashkent_city", "Toshkent shahri"),
                    ("andijan", "Andijon viloyati"),
                    ("bukhara", "Buxoro viloyati"),
                    ("fergana", "Farg'ona viloyati"),
                    ("jizzakh", "Jizzax viloyati"),
                    ("khorezm", "Xorazm viloyati"),
                    ("namangan", "Namangan viloyati"),
                    ("navoi", "Navoiy viloyati"),
                    ("kashkadarya", "Qashqadaryo viloyati"),
                    ("samarkand", "Samarqand viloyati"),
                    ("syrdarya", "Sirdaryo viloyati"),
                    ("surkhandarya", "Surxondaryo viloyati"),
                    ("tashkent_region", "Toshkent viloyati"),
                    ("karakalpakstan", "Qoraqalpog'iston Respublikasi"),
                ],
                max_length=100,
                verbose_name="Регион",
            ),
        ),
        migrations.CreateModel(
            name="BotBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Внутреннее название для менеджера",
                        max_length=200,
                        verbose_name="Название",
                    ),
                ),
                ("text_ru", models.TextField(blank=True, verbose_name="Текст (RU)")),
                ("text_uz", models.TextField(blank=True, verbose_name="Текст (UZ)")),
                ("text_en", models.TextField(blank=True, verbose_name="Текст (EN)")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Опционально — прикрепить фото к рассылке",
                        null=True,
                        upload_to="bot/broadcasts/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Например: Узнать подробнее",
                        max_length=100,
                        null=True,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "Все пользователи"),
                            ("ru", "Только русскоязычные"),
                            ("uz", "Только узбекоязычные"),
                            ("en", "Только англоязычные"),
                            ("hot", "Горячие клиенты"),
                            ("vip", "VIP клиенты"),
                            ("active_30", "Активные за 30 дней"),
                            ("region", "По региону"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "target_region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tashkent_city", "Toshkent shahri"),
                            ("andijan", "Andijon viloyati"),
                            ("bukhara", "Buxoro viloyati"),
                            ("fergana", "Farg'ona viloyati"),
                            ("jizzakh", "Jizzax viloyati"),
                            ("khorezm", "Xorazm viloyati"),
                            ("namangan", "Namangan viloyati"),
                            ("navoi", "Navoiy viloyati"),
                            ("kashkadarya", "Qashqadaryo viloyati"),
                            ("samarkand", "Samarqand viloyati"),
                            ("syrdarya", "Sirdaryo viloyati"),
                            ("surkhandarya", "Surxondaryo viloyati"),
                            ("tashkent_region", "Toshkent viloyati"),
                            ("karakalpakstan", "Qoraqalpog'iston Respublikasi"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Регион (если выбран по региону)",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Оставить пустым = отправить сразу после статуса 'Запланирована'",
                        null=True,
                        verbose_name="Запланировано на",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("scheduled", "Запланирована"),
                            ("sending", "Отправляется"),
                            ("done", "Отправлена"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(default=0, verbose_name="Получателей"),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(default=0, verbose_name="Отправлено"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ошибок"),
                ),
                (
                    "blocked_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Заблокировали бота"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено в"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Рассылка",
                "verbose_name_plural": "Бот — Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Уникальный идентификатор текста. Например: welcome, main_menu, td_success",
                        max_length=100,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("uz", "O'zbekcha"),
                            ("en", "English"),
                        ],
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Поддерживает HTML теги: <b>, <i>, <code>. Переменные: {name}, {phone}",
                        verbose_name="Текст",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Где используется этот текст",
                        max_length=200,
                        verbose_name="Описание (для менеджера)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Бот — Текст",
                "verbose_name_plural": "Бот — Тексты",
                "ordering": ["key", "language"],
                "unique_together": {("key", "language")},
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tashkent_city", "Toshkent shahri"),
                            ("andijan", "Andijon viloyati"),
                            ("bukhara", "Buxoro viloyati"),
                            ("fergana", "Farg'ona viloyati"),
                            ("jizzakh", "Jizzax viloyati"),
                            ("khorezm", "Xorazm viloyati"),
                            ("namangan", "Namangan viloyati"),
                            ("navoi", "Navoiy viloyati"),
                            ("kashkadarya", "Qashqadaryo viloyati"),
                            ("samarkand", "Samarqand viloyati"),
                            ("syrdarya", "Sirdaryo viloyati"),
                            ("surkhandarya", "Surxondaryo viloyati"),
                            ("tashkent_region", "Toshkent viloyati"),
                            ("karakalpakstan", "Qoraqalpog'iston Respublikasi"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ru", "Русский"),
                            ("uz", "O'zbekcha"),
                            ("en", "English"),
                        ],
                        default="ru",
                        max_length=5,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("interested", "Интересующийся"),
                            ("hot", "Горячий"),
                            ("client", "Клиент"),
                            ("vip", "VIP"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус клиента",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Пользователь нажал Stop или заблокировал бота",
                        verbose_name="Заблокировал бота",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления включены"
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        help_text="Код из ссылки ?start=ref_XXXXX",
                        max_length=50,
                        null=True,
                        verbose_name="Реферальный код",
                    ),
                ),
                (
                    "total_requests",
                    models.PositiveIntegerField(default=0, verbose_name="Всего заявок"),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="main.telegramuser",
                        verbose_name="Пригласил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Пользователь",
                "verbose_name_plural": "Бот — Пользователи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestDriveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Имя клиента"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                ("preferred_date", models.DateField(verbose_name="Желаемая дата")),
                (
                    "preferred_time",
                    models.CharField(
                        help_text="Например: 10:00",
                        max_length=10,
                        verbose_name="Желаемое время",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("confirmed", "Подтверждена"),
                            ("visited", "Клиент пришёл"),
                            ("no_show", "Не явился"),
                            ("cancelled", "Отменена"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание отправлено"
                    ),
                ),
                (
                    "feedback_requested",
                    models.BooleanField(
                        default=False, verbose_name="Запрос отзыва отправлен"
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий менеджера"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_drive_requests",
                        to="main.dealer",
                        verbose_name="Дилер",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_drive_requests",
                        to="main.product",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_drives",
                        to="main.telegramuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Заявка тест-драйв",
                "verbose_name_plural": "Бот — Заявки тест-драйв",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="main.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="main.telegramuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — Избранное",
                "verbose_name_plural": "Бот — Избранное",
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="ProductViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "last_viewed",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последний просмотр"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="main.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="main.telegramuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот — История просмотров",
                "verbose_name_plural": "Бот — История просмотров",
                "ordering": ["-last_viewed"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
