# Generated by Django 5.2.6 on 2026-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_bot_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotFSMState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Бот — FSM состояние",
                "verbose_name_plural": "Бот — FSM состояния",
            },
        ),
    ]
