# Generated by Django 5.2.7 on 2025-11-04 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_newsblock_title_en_newsblock_title_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsblock",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="newsblock",
            name="text_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="newsblock",
            name="text_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="newsblock",
            name="text_uz",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
    ]
