# Generated by Django 5.1.2 on 2026-04-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_bot_fsm_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Учредители, Генеральный директор, Отдел продаж', max_length=200, verbose_name='Название блока')),
                ('title_uz', models.CharField(help_text='Например: Учредители, Генеральный директор, Отдел продаж', max_length=200, null=True, verbose_name='Название блока')),
                ('title_ru', models.CharField(help_text='Например: Учредители, Генеральный директор, Отдел продаж', max_length=200, null=True, verbose_name='Название блока')),
                ('title_en', models.CharField(help_text='Например: Учредители, Генеральный директор, Отдел продаж', max_length=200, null=True, verbose_name='Название блока')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': ' - Команда: блок/отдел',
                'verbose_name_plural': 'Команда — Блоки/отделы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_uz', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемый размер: 400×400 px', null=True, upload_to='team/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок внутри блока')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.teamdepartment', verbose_name='Блок/отдел')),
            ],
            options={
                'verbose_name': ' - Команда: сотрудник',
                'verbose_name_plural': 'Команда — Сотрудники',
                'ordering': ['department__order', 'order'],
            },
        ),
    ]
