# Generated by Django 5.2.6 on 2026-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_team_department_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "company",
                    models.CharField(max_length=200, verbose_name="Компания/фирма"),
                ),
                (
                    "contact",
                    models.CharField(
                        max_length=100, verbose_name="Контакт (телефон или Telegram)"
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("advertising", "Реклама"),
                            ("supplies", "Поставки"),
                            ("it", "IT услуги"),
                            ("finance", "Финансы"),
                            ("logistics", "Логистика"),
                            ("media", "Медиа"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Тип предложения",
                    ),
                ),
                (
                    "proposal_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="bot/partners/",
                        verbose_name="Файл КП",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("viewed", "Просмотрена"),
                            ("in_work", "В работе"),
                            ("rejected", "Отклонена"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
            options={
                "verbose_name": "Бот — Партнёрское предложение",
                "verbose_name_plural": "Бот — Партнёрские предложения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="botmenuitem",
            name="key",
            field=models.CharField(
                choices=[
                    ("catalog", "🚗 Каталог"),
                    ("dealers", "🏢 Дилеры"),
                    ("news", "📰 Новости"),
                    ("promotions", "🎯 Акции"),
                    ("test_drive", "📋 Тест-драйв"),
                    ("lead", "📞 Оставить заявку"),
                    ("leasing", "💰 Лизинг"),
                    ("faq", "❓ FAQ"),
                    ("contacts", "📍 Контакты"),
                    ("profile", "👤 Профиль"),
                    ("language", "🌐 Язык"),
                    ("partner", "🤝 Сотрудничество"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Ключ",
            ),
        ),
    ]
