# Generated by Django 5.1.2 on 2026-05-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_partnerapplication_alter_botmenuitem_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'X (Twitter)'), ('custom', 'Другая')], max_length=20, verbose_name='Соцсеть')),
                ('title', models.CharField(blank=True, help_text='Заполните только для варианта "Другая"', max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.ImageField(blank=True, help_text='Загружайте только для варианта "Другая". Для известных соцсетей иконка берётся автоматически.', null=True, upload_to='socials/', verbose_name='Иконка (своя)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Название (UZ)')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('url', models.CharField(help_text='Пример: /about/ или /products/?category=samosval — для родителя с подменю используйте javascript:void(0)', max_length=300, verbose_name='URL')),
                ('location', models.CharField(choices=[('header', 'Хедер'), ('footer', 'Футер'), ('both', 'Хедер + Футер')], default='header', max_length=10, verbose_name='Место')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Открывать в новой вкладке')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.navitem', verbose_name='Родительский пункт (подменю)')),
            ],
            options={
                'verbose_name': 'Навигация — пункт меню',
                'verbose_name_plural': 'Навигация — меню (хедер/футер)',
                'ordering': ['order'],
            },
        ),
    ]
