# Generated by Django 5.1.2 on 2026-05-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_nav_and_socials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order'], 'verbose_name': 'Навигация — Социальная сеть', 'verbose_name_plural': 'Навигация — Социальные сети'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='TeamMemberLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: LinkedIn, Личный сайт, Telegram', max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(blank=True, default='ph-link', help_text='Класс Phosphor-иконки: ph-globe, ph-linkedin-logo, ph-telegram-logo и т.д.', max_length=60, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.teammember', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': ' - Команда: ссылка сотрудника',
                'verbose_name_plural': 'Команда — Ссылки сотрудников',
                'ordering': ['order'],
            },
        ),
    ]
