# Generated by Django 5.1.2 on 2026-05-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_teammember_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': ' - Команда: сотрудник', 'verbose_name_plural': 'Команда — Сотрудники'},
        ),
    ]
