# Generated by Django 5.1.2 on 2026-06-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_shop_and_image_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, help_text='Присваивается при подтверждении. Сбрасывается каждый Новый год.', null=True, verbose_name='Год')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Сквозной номер внутри года (1, 2, 3 ...). Пусто = черновик.', null=True, verbose_name='Номер')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('in_transit', 'В пути'), ('delivered', 'Доставлено')], db_index=True, default='pending_payment', help_text='После подтверждения — "Ожидание оплаты". Меняется админом.', max_length=20, verbose_name='Статус')),
                ('buyer_company_name', models.CharField(blank=True, max_length=255, verbose_name='Покупатель — юр. название')),
                ('buyer_inn', models.CharField(blank=True, max_length=20, verbose_name='Покупатель — ИНН')),
                ('buyer_contract_number', models.CharField(blank=True, max_length=100, verbose_name='Покупатель — № договора')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итоговая сумма (UZS)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='main.dealerprofile', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Магазин — Счёт',
                'verbose_name_plural': 'Магазин — Счета',
                'ordering': ['-year', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.invoice', verbose_name='Счёт')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.sparepart', verbose_name='Запчасть (если ещё есть в БД)')),
            ],
            options={
                'verbose_name': 'Позиция счёта',
                'verbose_name_plural': 'Позиции счёта',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('year', 'number'), name='invoice_year_number_unique'),
        ),
    ]
