# Generated by Django 5.1.2 on 2026-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='role',
            field=models.CharField(choices=[('dealer', 'Дилер'), ('service', 'Сотрудник сервиса'), ('accountant', 'Бухгалтер')], db_index=True, default='dealer', help_text='Дилер — покупатель. Сервис — обработка заказов и склад. Бухгалтер — оплата.', max_length=20, verbose_name='Роль'),
        ),
    ]
