# Generated by Django 5.1.2 on 2026-08-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_dealerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если заполнено, обычная цена зачёркивается, а рядом показывается эта. Должна быть меньше обычной цены. Чтобы убрать скидку — очистите поле', max_digits=15, null=True, verbose_name='Цена со скидкой (UZS)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_old',
            field=models.CharField(blank=True, help_text="Заполняйте только при акции: эта цена будет зачёркнута рядом с ценой для слайдера. Например: '455 000 000 sum'", max_length=100, null=True, verbose_name='Старая цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_old_en',
            field=models.CharField(blank=True, help_text="Заполняйте только при акции: эта цена будет зачёркнута рядом с ценой для слайдера. Например: '455 000 000 sum'", max_length=100, null=True, verbose_name='Старая цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_old_ru',
            field=models.CharField(blank=True, help_text="Заполняйте только при акции: эта цена будет зачёркнута рядом с ценой для слайдера. Например: '455 000 000 sum'", max_length=100, null=True, verbose_name='Старая цена для слайдера'),
        ),
        migrations.AddField(
            model_name='product',
            name='slider_price_old_uz',
            field=models.CharField(blank=True, help_text="Заполняйте только при акции: эта цена будет зачёркнута рядом с ценой для слайдера. Например: '455 000 000 sum'", max_length=100, null=True, verbose_name='Старая цена для слайдера'),
        ),
    ]
