# Generated by Django 5.1.2 on 2026-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_product_discount_price_product_slider_price_old_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название группы')),
                ('chat_type', models.CharField(blank=True, max_length=20, verbose_name='Тип чата')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Бот всё ещё в группе')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Бот добавлен')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Бот удалён')),
            ],
            options={
                'verbose_name': 'Бот — Группа',
                'verbose_name_plural': 'Бот — Группы',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='botbroadcast',
            name='send_to_groups',
            field=models.BooleanField(default=False, help_text='Помимо аудитории выше — продублировать в каждую активную группу/канал, куда добавлен бот (см. Бот — Группы). Текст берётся на русском.', verbose_name='Также отправить во все группы бота'),
        ),
    ]
