# Generated by Django 5.1.2 on 2026-08-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_botgroup_botbroadcast_send_to_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('message_id', models.BigIntegerField(verbose_name='Message ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('revoked', models.BooleanField(db_index=True, default=False, verbose_name='Отозвано')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано в')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='main.botbroadcast', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Бот — Доставка рассылки',
                'verbose_name_plural': 'Бот — Доставки рассылок',
                'indexes': [models.Index(fields=['broadcast', 'revoked'], name='main_broadc_broadca_9ee569_idx')],
            },
        ),
    ]
