# Generated by Django 5.1.2 on 2026-09-02 05:55

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_broadcastdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbroadcast',
            name='video',
            field=models.FileField(blank=True, help_text='Опционально — mp4/mov/gif, не более 10 МБ. Взаимоисключимо с изображением выше: заполнено только одно из двух.', null=True, upload_to='bot/broadcasts/video/', validators=[main.validators.validate_broadcast_video], verbose_name='Видео/GIF'),
        ),
    ]
