# Generated by Django 5.1.2 on 2026-09-03 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_botbroadcast_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Произвольные пары ключ-значение, например: {"wheelbase_mm": 3800}', verbose_name='Дополнительные данные (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Родительская модель',
                'verbose_name_plural': 'Родительские модели',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='truck',
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Платформа/шасси, на которой построен этот вариант кузова. Пока не используется на сайте — задел на будущее.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.parentmodel', verbose_name='Родительская модель (опционально)'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='parent_model',
            field=models.ForeignKey(blank=True, help_text='Привязка к платформе/шасси — деталь считается подходящей всем вариантам кузова на этой платформе. Можно оставить пустым.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='main.parentmodel', verbose_name='Родительская модель (опционально)'),
        ),
    ]
