# Generated by Django 5.1.2 on 2026-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_parentmodel_remove_sparepart_truck_product_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='parent_model',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='parent_models',
            field=models.ManyToManyField(blank=True, help_text='Привязка к одной или нескольким платформам/шасси — деталь считается подходящей всем вариантам кузова на каждой из них. Можно оставить пустым.', related_name='spare_parts', to='main.parentmodel', verbose_name='Родительские модели (опционально)'),
        ),
    ]
